### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by Fersoil** [xai4space/meteors#3]
add calculation of coverage in tests, could be done using `coverage`

**Comment by Fersoil** [comment]
@pbiecek it seems that codecov app still requires updating some more permissions, and this action needs to be performed by the organisation owner

**Comment by pbiecek** [comment]
added
the coverage should be visible here:
https://app.codecov.io/gh/xai4space/meteors/

**Comment by WolodjaZ** [comment]
Closing the issue as it was resolved
