### ISSUE TITLE
precommits

### ISSUE THREAD

**Issue by Fersoil** [xai4space/meteors#4]
solve precommit issues

workflows to include: 
- `ruff`
- `prettier`

it is to decide whether will I use `mypy`, it could be useful, but produces unfixable errors

**Comment by Fersoil** [comment]
@WolodjaZ ruff reports errors if created any fixes. imho should inform user about the changes, but fix the code without throwing errors

**Comment by Fersoil** [comment]
Reopening again, since the issue is still not fixed. It seems that the problem is also with the `pre-commit` hooks, which are run before the ruff formatter. 

I will remove the code formatting hooks from `https://github.com/pre-commit/pre-commit-hooks`.

**Comment by Fersoil** [comment]
Additional remark on pre-commits: 
It is somehow irritating that by default precommit fail if it makes any changes. Linked thread with this topic: https://stackoverflow.com/questions/58398995/black-as-pre-commit-hook-always-fails-my-commits

**Comment by WolodjaZ** [comment]
The authors mention that this is desired way of using recommits as developer always needs to check the changes that for example formatters suggest. But I agree that this kinda sucks in CI and I will think about best solution for this case.

**Comment by WolodjaZ** [comment]
Interesting [discussion](https://www.reddit.com/r/git/comments/16ke0xa/arguments_for_and_against_precommit_hooks/) @Fersoil
