### ISSUE TITLE
feat: aggregate attribution maps

### ISSUE THREAD

**Issue by Fersoil** [xai4space/meteors#56]
Perturbation and gradient attribution methods provide pixel-based attributions. To make this attribution comparable with LIME attributions we propose to aggregate the pixel-based attributions. 

We could group the attribution maps by channels or by spatial positions.

This approach could also make reading information from the charts easier. Since user would not need to perform the aggregation by themself, but rather look at the easier to understand data - for instance, user could easily notice, that the infrared band gives is much more important for the model than the ultraviolet.

**Comment by Fersoil** [comment]
#45 #44 are needed to be resolved first to implement this feature

**Comment by WolodjaZ** [comment]
Resolved with #71
