### ISSUE TITLE
fix: band names with groups of indices

### ISSUE THREAD

**Issue by Fersoil** [xai4space/meteors#81]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in Meteors rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of Meteors.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Reproduction steps

band_mask, band_names = lime.get_band_mask(hsi_0, ["R", ["B", "G"]])

spectral_attributes = lime.get_spectral_attributes(
    hsi_0,  # HSI data
    band_mask=band_mask,  # Band mask
    target=1,  # class analyzed - K - potassium
    band_names=band_names,  # Band names
    n_samples=10,  # Number of perturbation, the more the better explainer is trained but the analsys is slower
)

# this example fails, because the spectral attributes fails to be created

### Error Message and Stack Trace (if applicable)

![image](https://github.com/user-attachments/assets/893ba76a-60be-4a52-9812-cd8f18c57ed9)

**Comment by WolodjaZ** [comment]
Already fixed
