### ISSUE TITLE
feat: input-wise aggregation of segmentation problem type

### ISSUE THREAD

**Issue by Fersoil** [xai4space/meteors#97]
### Feature Description

Instead of aggregating the output of segmentation attributions (using e.g. one-hot encoding) we can also aggregate the inputs for the spatial case.

### Use Case

This use case is limited for the spatial attribution (probably) and in general should output a spatial attribution object without the mask of segments

**Comment by WolodjaZ** [comment]
@pbiecek could you elaborate more about the approach? In our current aggregation approach, we modify the model output to a 1D tensor. We've implemented a method that counts the occurrence of each class (based on the argmax) per pixel, resulting in a 1D tensor where each index indicates the number of occurrences of that class in the output. If we want to aggregate differently, could you specify what the 1D tensor should represent and how we should compute it? What alternative aggregation methods would you suggest?
